DESCUENTO_NUEVO = 0.05
DESCUENTO_REGULAR = 0.03
DESCUENTO_BECA = 0.20
DESCUENTO_VIRTUAL = 25
RECARGO_PRESENCIAL = 50
DESCUENTO_DICIEMBRE = 30

TIPOS_ESTUDIANTE_VALIDOS = ("nuevo", "regular")
MODALIDADES_VALIDAS = ("virtual", "presencial")
